name: "Publish to npmjs.org"

on:
    release:
        types: [published]

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v4
              with:
                  version: 9
            - uses: actions/setup-node@v4
              with:
                  cache: "pnpm"
                  node-version: "22.x"
                  registry-url: "https://registry.npmjs.org"
            - run: pnpm install --frozen-lockfile
            - run: pnpm build
            - run: pnpm test
            - run: NPM_CONFIG_PROVENANCE=true pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
